services:
  mysql:
    image: mysql:8.0
    container_name: sec-commerce-db
    restart: always
    tty: true
    volumes:
      - volume-sec-commerce-db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      default_authentication_plugin: mysql_native_password
    networks:
      - sec-commerce-app
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      - PMA_HOST=sec-commerce-db
    depends_on:
      - mysql
    networks:
      - sec-commerce-app

  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: sec-commerce-php
    restart: always
    tty: true
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    env_file:
      - path: ./.env
        required: true
    depends_on:
      - mysql
    networks:
      - sec-commerce-app
volumes:
  volume-sec-commerce-db:
    driver: local
networks:
  sec-commerce-app:
    driver: bridge